name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: setup gradle
        uses: gradle/actions/setup-gradle@v4
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build all versions
        run: ./gradlew chiseledBuild
      - name: upload 1.20.4
        uses: actions/upload-artifact@v4
        with:
          name: bedrock-loader-mc1.20.4
          path: versions/1.20.4/build/libs/bedrock-loader-*[!s].jar
      - name: upload 1.21.1
        uses: actions/upload-artifact@v4
        with:
          name: bedrock-loader-mc1.21.1
          path: versions/1.21.1/build/libs/bedrock-loader-*[!s].jar
      - name: upload 1.21.2
        uses: actions/upload-artifact@v4
        with:
          name: bedrock-loader-mc1.21.2
          path: versions/1.21.2/build/libs/bedrock-loader-*[!s].jar
      - name: upload 1.21.3
        uses: actions/upload-artifact@v4
        with:
          name: bedrock-loader-mc1.21.3
          path: versions/1.21.3/build/libs/bedrock-loader-*[!s].jar
      - name: upload 1.21.4
        uses: actions/upload-artifact@v4
        with:
          name: bedrock-loader-mc1.21.4
          path: versions/1.21.4/build/libs/bedrock-loader-*[!s].jar
      - name: upload 1.21.5
        uses: actions/upload-artifact@v4
        with:
          name: bedrock-loader-mc1.21.5
          path: versions/1.21.5/build/libs/bedrock-loader-*[!s].jar
      - name: upload 1.21.6
        uses: actions/upload-artifact@v4
        with:
          name: bedrock-loader-mc1.21.6
          path: versions/1.21.6/build/libs/bedrock-loader-*[!s].jar
      - name: upload 1.21.7
        uses: actions/upload-artifact@v4
        with:
          name: bedrock-loader-mc1.21.7
          path: versions/1.21.7/build/libs/bedrock-loader-*[!s].jar
      - name: upload 1.21.8
        uses: actions/upload-artifact@v4
        with:
          name: bedrock-loader-mc1.21.8
          path: versions/1.21.8/build/libs/bedrock-loader-*[!s].jar
      - name: upload 1.21.9
        uses: actions/upload-artifact@v4
        with:
          name: bedrock-loader-mc1.21.9
          path: versions/1.21.9/build/libs/bedrock-loader-*[!s].jar
      - name: upload 1.21.10
        uses: actions/upload-artifact@v4
        with:
          name: bedrock-loader-mc1.21.10
          path: versions/1.21.10/build/libs/bedrock-loader-*[!s].jar
      - name: upload 1.21.11
        uses: actions/upload-artifact@v4
        with:
          name: bedrock-loader-mc1.21.11
          path: versions/1.21.11/build/libs/bedrock-loader-*[!s].jar
